---
title: Licht van LED's verspreiden
hero_image: images/banner.png
description: Hoe kan je licht van LED's verspreiden
version: 4
listed: false
copyedit: false
last_tested: "2022-02-17"
steps:
  - title: Licht van LED's verspreiden
