title: Diffuse lights from LEDs
hero_image: images/banner.png
description: How to diffuse lights from LEDs
version: 4
listed: false
copyedit: false
last_tested: "2022-02-17"
steps:
  - title: Diffuse lights from LEDs
