---
title: Lumières diffuses des LED
hero_image: images/banner.png
description: Comment diffuser les lumières des LED
version: 4
listed: false
copyedit: false
last_tested: "2022-02-17"
steps:
  - title: Lumières diffuses des LED
